### ISSUE TITLE
Play mp3 file?

### ISSUE THREAD

**Issue by sohnkarlsruhe** [petro-kushchak/homebridge-homepod-radio#11]
It is possible to play only mp3 file instead of stream?

**Comment by petro-kushchak** [comment]
Hi - technically it's possible, what's the use case?

**Comment by feardamhan** [comment]
In my case I’d like to be able to use this plugin to play a sound on a HomePod when an event occurs. For instance when a homenbridge-security-system alarm is triggered that it would play a burglar-alarm.mp3 on selected HomePods.

**Comment by petro-kushchak** [comment]
Make sense - I will add HTTP endpoint which could be triggered from automation to play mp3 on specified HomePod

**Comment by feardamhan** [comment]
That would be awesome. Thanks.

**Comment by sohnkarlsruhe** [comment]
That’s the same case. Without apple music I can’t play a warning or information on the HomePod. Thanks for your work

**Comment by petro-kushchak** [comment]
I pushed homebridge-homepod-radio v1.1.40-beta.0 with local mp3/wav playback support, would be great if you could check it out, thanks!

**Comment by feardamhan** [comment]
Not quite clear on how to configure. You give an example of "http://homebridge.local:4567/play/hello.mp3" - should that be in the mediaPath json entry? Or the radioUrl? Neither? Could you dump a quick sample json config here for reference?

**Comment by feardamhan** [comment]
Still struggling to get this to work. Based on the current readme, is this all thats needed to play a local mp3 file?

`         {
            "platform": "HomepodRadioPlatform",
            "serialNumber": "20020105:00",
            "homepodId": "D4A33D61C84E",
            "httpPort": 4567,
            "mediaPath": "/var/www/media"
        }`

What should the port be in this case? My mp3 is in the above folder, but I dont need a port to hit it. For me, this link works in a browser to stream the file http://192.168.15.31/media/Burglar-alarm-sound.mp3

I'm also not clear on how to setup the automation on the Home app. I assume you need to add the speaker accessory to Homekit using the homebridge pin. I've done that successfully. However I dont see any mention of that speaker being selected in the setup of the Automation  / Shortcut. I've tried messing about with different settings, but I cant get the mp3 playing on the HomePod when I test the automation. I must be missing something simple I guess.

**Comment by petro-kushchak** [comment]
The idea is that to play mp3 file on your homepod, you just have to make HTTP GET request to plugin which should listen requests on  "httpPort".

So, assuming:
1. homebridge server is running on host "homebridge.local" 
2. hello.mp3 file is on the same server on /var/www/media
3. Plugin's "httpPort" is set to 4567
4. Plugin's "mediaPath" is set to /var/www/media

You can trigger playback of hello.mp3 even from browser by navigating to: 
http://homebridge.local:4567/play/hello.mp3 

Same could be done from HomeKit automation using shortcuts (I've updated readme with example screenshot)

Let me know if this is more clear - will put more details/examples into readme

**Comment by feardamhan** [comment]
Thanks for continuing to help. 

So I my configuration of the plugin is now very simple. As follows:

        {
            "homepodId": "D4A33D61C84E",
            "verboseModel": false,
            "volumeControl": false,
            "platform": "HomepodRadioPlatform",
            "httpPort": 7654,
            "mediaPath": "/var/www/media"
        }

My mp3 file is in /var/www/media

From a browser, this link does not work
http://192.168.15.31:7654/play/Burglar-alarm-sound.mp3

But this does work
http://192.168.15.31/media/Burglar-alarm-sound.mp3

**Comment by petro-kushchak** [comment]
Is your homebridge server IP 192.168.15.31?

If so what you get from terminal when you run:

curl -v "http://192.168.15.31:7654/play/Burglar-alarm-sound.mp3"

**Comment by feardamhan** [comment]
*   Trying 192.168.15.31...
* TCP_NODELAY set
* Connection failed
* connect to 192.168.15.31 port 7654 failed: Connection refused
* Failed to connect to 192.168.15.31 port 7654: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 192.168.15.31 port 7654: Connection refused

**Comment by petro-kushchak** [comment]
Looks like there is some issue with enabling HTTP port (maybe try another port?), could you check for errors in homebridge logs?

If everything is ok you should see message:

[HomepodRadioPlatform] Setting up HTTP server on port 7654...

**Comment by feardamhan** [comment]
This is all that shows in the log. No mention of HTTP Port being set

[2/14/2022, 23:31:02] [HomepodRadioPlatform] Platform: shutdown...
[2/14/2022, 23:31:02] [HomepodRadioPlatform] [HomePod Radio] Skipped storing state
[2/14/2022, 23:31:18] Registering platform '@petro-kushchak/homebridge-homepod-radio.HomepodRadioPlatform'
[2/14/2022, 23:31:18] [HomepodRadioPlatform] Initializing HomepodRadioPlatform platform...
[2/14/2022, 23:31:18] [HomepodRadioPlatform] Loaded 1 radios: HomePod Radio
[2/14/2022, 23:31:18] [HomepodRadioPlatform] Finished initializing platform: HomepodRadioPlatform
[2/14/2022, 23:31:18] [HomepodRadioPlatform] [HomePod Radio] Storage path: /home/homebridge/.homebridge/HomepodRadioPlatform-0750a253-c2e3-4b74-b244-7c577a859ccd.status.json
[2/14/2022, 23:31:18] One of your plugins incorrectly registered an external accessory using the platform name (HomepodRadioPlatform) and not the plugin identifier. Please report this to the developer!
[2/14/2022, 23:31:20] [HomepodRadioPlatform] [HomePod Radio] Skipped reading state
[2/14/2022, 23:31:20] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/14/2022, 23:31:33] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/14/2022, 23:32:39] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/14/2022, 23:37:58] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/14/2022, 23:38:34] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 02:29:04] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 07:15:21] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 07:16:43] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 08:46:34] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 08:51:53] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 09:08:31] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 09:10:08] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 09:10:09] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 09:10:12] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2
[2/15/2022, 09:10:45] [HomepodRadioPlatform] [HomePod Radio] Triggered GET CurrentMediaState: 2

**Comment by petro-kushchak** [comment]
Which version of the plugin you are running? This feature should work starting from 1.1.40-beta.0 but according to logs its not starting HTTP server (so probably you are on the older version?)...

Also looks like I should add plugin version to logs :)

**Comment by feardamhan** [comment]
@petro-kushchak/homebridge-homepod-radio v1.1.34 is what it says under the tile in Homebridge. I installed the plugin via a search in the homebridge UI. I now see that you have a trigger_play_mp3 branch on GitHub, which I assume maps to the homebridge-homepod-radio v1.1.40-beta.0 version you mentioned above. Can you advise on how to install that version?

**Comment by petro-kushchak** [comment]
Installing beta's is not quite obvious - the easiest steps are:
1. With Hombridge UI, open Plugins Tab
2. Click on the "wrench" icon in the "Homepod mini radio support" box
3. Its weird, but select "Install Previous Version"
4. In the popup it will show all available plugin versions (including betas) - just select latest beta

Alternatively you can install from terminal:
> sudo npm install -g @petro-kushchak/homebridge-homepod-radio@1.1.40-beta.4

**Comment by petro-kushchak** [comment]
This error sometimes appears (looks like some bug in tvOS) - try to restart your Homepod 

Also you can try to test that your mp3 file works with HomePod (just in case to make sure your mp3 file is ok) by running from terminal:
> atvremote --id D4A33D61C84E stream_file=/var/www/media/Burglar-alarm-sound.mp3

**Comment by feardamhan** [comment]
I was testing hitting the homebridge plugin from a browser. Not yet tried to get the HomePod to play it (baby steps! :-) )

curl -v "http://192.168.15.31:7654/play/Burglar-alarm-sound.mp3" 

also returns the above error

So does that mean that even when I try to hit the mp3 via a browser it should output on the HomePod?

Also I just realised that its a original HomePod (not HomePod mini) I was testing on. Should that make a difference? It seems like the same OS on it.

**Comment by feardamhan** [comment]
OK. Further progress made. It does appear to play on both the HomePod and HomePod Mini.

Some further feedback/thoughts:

- Seems like there is no need for the accessory to be added to the HomeKit for that to work ( I guess thats only for the Siri voice command integration?)

- When the sensor is triggered I see the following in the logs:

[2/15/2022, 16:56:24] [Office HomePod Siren] [Office HomePod Siren] Cleared hearbeat null - stop requested
[2/15/2022, 16:56:24] [Office HomePod Siren] [Office HomePod Siren] Streaming finished - stop requested

- Not sure if that is right or not. The streaming isnt finished. In fact it hasn't even started. 
- Which leads me to my next point. It takes about 7-8 seconds before anything plays on the HomePod. Any idea why that would be?

- Lastly. When the streaming is started. How does on stop it? In my case it seems I need to wait for the duration of the 20 second mp3 file to play. I tried playing with adding the accessory and creating a scene that pauses the audio on the speaker accessory, but that doesn't seem to work
- Is there an option to loop the mp3 file?

Great progress in just a few days. Many thanks!

**Comment by sohnkarlsruhe** [comment]
Hi there,
I get the same error:
`pi@raspberrypi:~ $ atvremote --id 50BC960A71F1 stream_file=/home/pi/.homebridgeTools/mp3/hello.mp3
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 513, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 614, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 662, in _handle_device_command
    return await _exec_command(atv.stream, cmd, True, *cmd_args)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/raop/__init__.py", line 352, in stream_file
    await client.initialize(self.core.service.properties)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/raop/raop.py", line 457, in initialize
    await self._setup_session()
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/raop/raop.py", line 489, in _setup_session
    "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;"
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/rtsp.py", line 175, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/rtsp.py", line 266, in exchange
    allow_error=allow_error,
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/http.py", line 415, in send_and_receive
    response.code,
pyatv.exceptions.HttpError: RTSP/1.0 method SETUP failed with code 500: Internal Server Error

>>> An error occurred, full stack trace above
pi@raspberrypi:~ $ 
`

what did you do to solve it?

**Comment by feardamhan** [comment]
So it worked fine on my HomePod mini first time out. My original HomePod I'm not sure. I rebooted the it and it seemed to work fine since, but not sure if that was the actual fix.

**Comment by sohnkarlsruhe** [comment]
It works ( I used a m4a file)
It works with a single HomePod classic, but not with a stereo set


`pi@raspberrypi:~ $ atvremote --id D4A33D859B73 stream_file=/home/pi/.homebridgeTools/mp3/hello.mp3
2022-02-15 18:38:17 ERROR [pyatv.protocols.raop.raop]: Audio error received: [Errno 111] Connection refused
2022-02-15 18:38:17 WARNING [pyatv.protocols.raop.raop]: Connection closed while streaming audio
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/http.py", line 388, in send_and_receive
    await asyncio.wait_for(event.wait(), timeout=4)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 513, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 614, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 662, in _handle_device_command
    return await _exec_command(atv.stream, cmd, True, *cmd_args)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/raop/__init__.py", line 392, in stream_file
    await client.send_audio(audio_file, metadata)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/protocols/raop/raop.py", line 604, in send_audio
    await self.rtsp.teardown(self.context.rtsp_session)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/rtsp.py", line 225, in teardown
    return await self.exchange("TEARDOWN", headers={"Session": rtsp_session})
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/rtsp.py", line 266, in exchange
    allow_error=allow_error,
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/support/http.py", line 391, in send_and_receive
    raise TimeoutError(f"no response to {method} {uri} ({protocol})") from ex
TimeoutError: no response to TEARDOWN rtsp://192.168.0.115/3206115740 (RTSP/1.0)

>>> An error occurred, full stack trace above
`

**Comment by sohnkarlsruhe** [comment]
Thanks for the fast feature release
