### ISSUE TITLE
Pairing issue with Homepod mini, atvremote scan = Pairing: Disabled

### ISSUE THREAD

**Issue by drpodmeer** [petro-kushchak/homebridge-homepod-radio#3]
Hi Petro, 

What a great idea your plug-in, thank you so much!

Unfortunately the plug in does not work for me, I can pair it to Homekit App but unfortunately the homepod does not play music.

in the homebridge log protocol i get  this message:

A platform configured a external accessory under the plugin name 'homebridge-homepod-radio-platform'. However no loaded plugin could be found for the name!

my config:

{
    "platform": "HomepodRadioPlatform",
    "name": "Homepod Radio",
    "model": "BBC - Radio 1",
    "homepodId": "58D34940A3EC",
    "radioUrl": "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one"
}

i did all steps in the readme, can i provide you with more details?

[09/01/2022, 20:01:23] [Radio] Finished initializing platform: HomepodRadioPlatform
[09/01/2022, 20:01:23] A platform configured a external accessory under the plugin name 'homebridge-homepod-radio-platform'. However no loaded plugin could be found for the name!
[09/01/2022, 20:01:23] Radio 6D86 is running on port 32935.
[09/01/2022, 20:01:23] Please add [Radio 6D86] manually in Home app. Setup Code: 812-89-820

**When i press the Radio button on Homekit, i get this messages:**

[Radio 6D86@Volume] The read handler for the characteristic 'Volume' on the accessory 'Radio 6D86' was slow to respond!
[09/01/2022, 20:30:13] [Radio] Triggered GET CurrentMediaState: 0
[09/01/2022, 20:30:13] [Radio] Triggered GET getVolume
[Radio 6D86@Volume] The read handler for the characteristic 'Volume' on the accessory 'Radio 6D86' was slow to respond!
[09/01/2022, 20:30:16] [Radio] Triggered GET CurrentMediaState: 0
[09/01/2022, 20:30:16] [Radio] Triggered GET getVolume
[Radio 6D86@Volume] The read handler for the characteristic 'Volume' on the accessory 'Radio 6D86' was slow to respond!
[09/01/2022, 20:30:20] [Radio] Streaming finished
[09/01/2022, 20:30:21] [Radio] Triggered GET CurrentMediaState: 2
[09/01/2022, 20:30:21] [Radio] Triggered GET getVolume
[09/01/2022, 20:30:24] [Radio] Triggered GET CurrentMediaState: 2
[09/01/2022, 20:30:24] [Radio] Triggered GET getVolume
[09/01/2022, 20:30:26] [Radio] Triggered GET CurrentMedi

**Environment**:
Node.js Version: v16.13.1
NPM Version:v8.3.0
Homebridge Version: 1.3.9
Operating System: Raspbian
RASPBERRY PI 3 Model B

Name: Home Pod Küche
Model/SW: HomePod Mini, tvOS 15.2
Address: 192.168.1.244
MAC: 58:D3:49:40:A3:EC
Deep Sleep: False
Identifiers:
 - 58:D3:49:40:A3:EC
 - 58D34940A3EC
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled

Thank you again for all your work!
Cheers Marlon

**Comment by petro-kushchak** [comment]
Hi, thanks for checking out the plugin! Its quite fresh and still require some testing/fixing...

In your case, 
1. >> no loaded plugin could be found for the name
This warning is ok, I will fix it at some moment - but it does not break plugin
2. Could you please add to the plugin configuration 
`"verboseMode": true
`
And send back logs (there should be much more noise in the logs with this setting :)
3. Try to connect to your Raspberry Pi and run manually (assuming 58D34940A3EC is your HomePod mini ID):
`
ffmpeg -i http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one -f mp3 - | atvremote --id 58D34940A3EC stream_file=-
`

**Comment by drpodmeer** [comment]
Hi, thanks for you answer!

getting this back in the Terminal, after step3.

**av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe**

pi@homebridge:~ $ ffmpeg -i http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one -f mp3 - | atvremote --id 58D34940A3EC stream_file=-
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
2022-01-09 22:05:13 ERROR [pyatv.protocols.airplay]: Failed to set up remote control channel
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 267, in _connect_rc
    await control.start(str(config.address), control_port, credentials)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/remote_control.py", line 56, in start
    self.verifier = await verify_connection(credentials, self.connection)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/auth/__init__.py", line 103, in verify_connection
    has_encryption_keys = await verifier.verify_credentials()
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/auth/hap_transient.py", line 47, in verify_credentials
    await self.http.post("/pair-pin-start", headers=_AIRPLAY_HEADERS)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/http.py", line 359, in post
    return await self.send_and_receive(
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/http.py", line 412, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: HTTP/1.1 method POST failed with code 400: Bad Request
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 513, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 604, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/__init__.py", line 110, in connect
    await atv.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/facade.py", line 565, in connect
    if await setup_data.connect():
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 927, in _connect
    await protocol.start()
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 127, in start
    await self.connection.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/mrp/connection.py", line 104, in connect
    await self.loop.create_connection(lambda: self, self.host, self.port)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.244', 0)

>>> An error occurred, full stack trace above
[mp3 @ 0x2f25370] Skipping 156 bytes of junk at 0.
Input #0, mp3, from 'http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one':
  Metadata:
    icy-br          : 128
    icy-pub         : 0
    icy-name        : BBC Radio
    icy-description : BBC Radio
    StreamTitle     : BBC Radio 1
  Duration: N/A, start: 0.000000, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, mp3, to 'pipe:':
  Metadata:
    icy-br          : 128
    icy-pub         : 0
    icy-name        : BBC Radio
    icy-description : BBC Radio
    StreamTitle     : BBC Radio 1
    TSSE            : Lavf58.45.100
    Stream #0:0: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavc58.91.100 libmp3lame
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
size=       1kB time=00:00:00.00 bitrate=4690.5kbits/s speed=0.0122x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 49.479168%
Conversion failed!


---------------------------------------------------------------------------------------------------------------------------
**this is the log in Homebridge Log in verbose mode**


09/01/2022, 22:09:20] [Radio] Triggered GET CurrentMediaState: 2
[09/01/2022, 22:09:20] [Radio] Triggered GET getVolume
[09/01/2022, 22:09:21] [Radio] Triggered SET TargetMediaState: 0
[09/01/2022, 22:09:21] [Radio] spawn ffmpeg: 606  atvremote: 607 []
[09/01/2022, 22:09:21] [Radio] ffmpeg error: ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
 []
[09/01/2022, 22:09:21] [Radio] Playback heartbeat, source: ffmpeg []
[Radio 6D86@@Volume] The read handler for the characteristic 'Volume' was slow to respond!
[09/01/2022, 22:09:24] [Radio] atvremote error: Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 513, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 604, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/__init__.py", line 110, in connect
    await atv.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/facade.py", line 565, in connect
    if await setup_data.connect():
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 927, in _connect
    await protocol.start()
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 127, in start
    await self.connection.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/mrp/connection.py", line 104, in connect
    await self.loop.create_connection(lambda: self, self.host, self.port)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.244', 0)

>>> An error occurred, full stack trace above
 []
[09/01/2022, 22:09:24] [Radio] Playback heartbeat, source: atvremote []
[09/01/2022, 22:09:24] [Radio] Triggered GET CurrentMediaState: 0
[09/01/2022, 22:09:24] [Radio] Triggered GET getVolume
[09/01/2022, 22:09:24] [Radio] atvremote exit: code 1 signal null []
[09/01/2022, 22:09:26] [Radio] Playback heartbeat, source: heartbeat []
[09/01/2022, 22:09:26] [Radio] Playback heartbeat, diff: 2131ms []
[09/01/2022, 22:09:26] [Radio] ffmpeg error: [mp3 @ 0x281b380] Skipping 175 bytes of junk at 0.
 []
[09/01/2022, 22:09:26] [Radio] Playback heartbeat, source: ffmpeg []
[09/01/2022, 22:09:26] [Radio] ffmpeg error: Input #0, mp3, from 'http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one':
  Metadata:
    icy-br          : 128
    icy-pub         : 0
    icy-name        : BBC Radio
    icy-description : BBC Radio
    StreamTitle     : BBC Radio 1
  Duration: N/A []
[09/01/2022, 22:09:26] [Radio] Playback heartbeat, source: ffmpeg []
[09/01/2022, 22:09:26] [Radio] ffmpeg error: , start: 0.000000, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
 []
[09/01/2022, 22:09:26] [Radio] Playback heartbeat, source: ffmpeg []
[09/01/2022, 22:09:26] [Radio] ffmpeg error: Output #0, mp3, to 'pipe:':
  Metadata:
    icy-br          : 128
    icy-pub         : 0
    icy-name        : BBC Radio
    icy-description : BBC Radio
    StreamTitle     : BBC Radio 1
    TIT2            : "Radio BBC"
    TSSE            : Lavf58.45.100
    Stream #0:0: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavc58.91.100 libmp3lame
 []
[09/01/2022, 22:09:26] [Radio] Playback heartbeat, source: ffmpeg []
 []/01/2022, 22:09:27] [Radio] ffmpeg error: size=      15kB time=00:00:00.91 bitrate= 133.1kbits/s speed= 1.8x    
[09/01/2022, 22:09:27] [Radio] Playback heartbeat, source: ffmpeg []
[Radio 6D86@Volume] The read handler for the characteristic 'Volume' on the accessory 'Radio 6D86' was slow to respond!
 []/01/2022, 22:09:27] [Radio] ffmpeg error: size=      31kB time=00:00:01.96 bitrate= 130.4kbits/s speed=1.95x    
[09/01/2022, 22:09:27] [Radio] Playback heartbeat, source: ffmpeg []
 []/01/2022, 22:09:28] [Radio] ffmpeg error: size=      48kB time=00:00:03.04 bitrate= 129.5kbits/s speed=2.01x    
[09/01/2022, 22:09:28] [Radio] Playback heartbeat, source: ffmpeg []
 []/01/2022, 22:09:28] [Radio] ffmpeg error: size=      64kB time=00:00:04.03 bitrate= 129.2kbits/s speed=   2x    
[09/01/2022, 22:09:28] [Radio] Playback heartbeat, source: ffmpeg []
[09/01/2022, 22:09:28] [Radio] Triggered GET CurrentMediaState: 0
[09/01/2022, 22:09:28] [Radio] Triggered GET getVolume
[09/01/2022, 22:09:31] [Radio] Playback heartbeat, source: heartbeat []
[09/01/2022, 22:09:31] [Radio] Playback heartbeat, diff: 2474ms []
[09/01/2022, 22:09:36] [Radio] Playback heartbeat, source: heartbeat []
[09/01/2022, 22:09:36] [Radio] Playback heartbeat, diff: 7475ms []
[09/01/2022, 22:09:36] [Radio] Playback heartbeat failed []
[09/01/2022, 22:09:38] [Radio] Received from device: 58D34940A3EC title: 2022-01-09 22:09:38 ERROR [pyatv.protocols.airplay]: Failed to set up remote control channel
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 267, in _connect_rc
    await control.start(str(config.address), control_port, credentials)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/remote_control.py", line 56, in start
    self.verifier = await verify_connection(credentials, self.connection)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/auth/__init__.py", line 103, in verify_connection
    has_encryption_keys = await verifier.verify_credentials()
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/airplay/auth/hap_transient.py", line 47, in verify_credentials
    await self.http.post("/pair-pin-start", headers=_AIRPLAY_HEADERS)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/http.py", line 359, in post
    return await self.send_and_receive(
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/http.py", line 412, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: HTTP/1.1 method POST failed with code 400: Bad Request
 []
[09/01/2022, 22:09:38] [Radio] Killing process: ffmpeg: 606  atvremote: 607 []
[09/01/2022, 22:09:38] [Radio] Streaming finished

**Comment by petro-kushchak** [comment]
Hi, looks like some issue with managing your HomePod mini with pyatv lib or specific setup is needed... 

Could you run one more test to make more clarity (probably it requires pairing...)? What is the output of:

```
atvremote scan
```

for your Homepod?

**Comment by drpodmeer** [comment]
This is the output:

Name: Home Pod Küche
Model/SW: HomePod Mini, tvOS 15.2
Address: 192.168.1.244
MAC: 58:D3:49:40:A3:EC

Deep Sleep: False
Identifiers:
 - 58:D3:49:40:A3:EC
 - 58D34940A3EC
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled

**Comment by petro-kushchak** [comment]
In my case I get:

```
       Name: HomePod
   Model/SW: HomePod Mini, tvOS 15.2
    Address: 192.168.1.7
        MAC: F4:34:F0:10:88:77
 Deep Sleep: False
Identifiers:
 - F4:34:F0:10:88:77
 - F434F0108877
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Unsupported
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
```

Looks like for some reason you have ```Pairing: Disabled``` which prevents your HomePod to accept media stream...

According to pyatv doc:
https://pyatv.dev/development/scan_pair_and_connect/#pairing-requirement

```const.PairingRequirement.Disabled - Pairing is generally supported by the protocol, but has been (temporarily) disabled by the device```

So, probably you could try to reset your Homepod and check if it comes back to ```Pairing: NotNeeded```


I will update readme with these findings...

**Comment by drpodmeer** [comment]
Hi Petro,

WupWup, now its working! thanks a lot, resetting the Homepod mini was the solution, this is my new Result:

Name: Küche
Model/SW: HomePod Mini, tvOS 15.2
Address: 192.168.1.244
MAC: 58:D3:49:40:A3:EC
 Deep Sleep: True
Identifiers:
 - 58:D3:49:40:A3:EC
 - 58D34940A3EC
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Unsupported
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded

**Comment by drpodmeer** [comment]
hi there

now after 30min. its again  Pairing: Disabled 

:/ bad luck

**Comment by petro-kushchak** [comment]
Try to change you Home settings in the Home app....

Hopefully this will help: https://support.apple.com/en-gb/guide/iphone/iphcbaf7e8f3/ios

**Comment by drpodmeer** [comment]
now its working :)

Home app settings:

1. Tap the Homes and Home Settings button.
2. Tap Home Settings > Allow Speaker & TV Access, then choose "**allow everyone**"
3. Important! Reboot the Homepod 

done

**Comment by drpodmeer** [comment]
Hello Petro

Now i get this error message, it was working two time, to play the radio.

pi@homebridge:~ $ ffmpeg -i http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one -f mp3 - | atvremote --id 58D34940A3EC stream_file=
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mp3 @ 0x2fdf370] Skipping 147 bytes of junk at 0.
Input #0, mp3, from 'http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one':
  Metadata:
    icy-br          : 128
    icy-pub         : 0
    icy-name        : BBC Radio
    icy-description : BBC Radio
    StreamTitle     : BBC Radio 1
  Duration: N/A, start: 0.000000, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, mp3, to 'pipe:':
  Metadata:
    icy-br          : 128
    icy-pub         : 0
    icy-name        : BBC Radio
    icy-description : BBC Radio
    StreamTitle     : BBC Radio 1
    TSSE            : Lavf58.45.100
    Stream #0:0: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavc58.91.100 libmp3lame
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 719, in _run_application
    return await cli_handler(loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 513, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 614, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 662, in _handle_device_command
    return await _exec_command(atv.stream, cmd, True, *cmd_args)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 685, in _exec_command
    value = await tmp(*args)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 331, in stream_file
    await client.initialize(self.service.properties)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/raop/raop.py", line 454, in initialize
    await self._setup_session()
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/raop/raop.py", line 483, in _setup_session
    resp = await self.rtsp.setup(
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/rtsp.py", line 175, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/rtsp.py", line 258, in exchange
    resp = await self.connection.send_and_receive(
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/http.py", line 412, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: RTSP/1.0 method SETUP failed with code 500: Internal Server Error

>>> An error occurred, full stack trace above
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
size=      11kB time=00:00:00.72 bitrate= 129.9kbits/s speed= 1.5x    
video:0kB audio:12kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
pi@homebridge:~ $ ffmpeg -i http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one -f mp3 - | atvremote --id 58D34940A3EC stream_file=-


_____________________________________________________________

Name: Küche
Model/SW: HomePod Mini, tvOS 15.2
Address: 192.168.1.244
MAC: 58:D3:49:40:A3:EC
 
Deep Sleep: False
Identifiers:
 - 58D34940A3EC
 - 58:D3:49:40:A3:EC
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded

**Comment by petro-kushchak** [comment]
Hi, I got this error only once on my HomePod mini after random streaming start/stop + air playing from other devices (it disappeared after HomePod restart). How often do you get it?
