### ISSUE TITLE
Error: code 470: Connection Authorization Required

### ISSUE THREAD

**Issue by mtthidoteu** [petro-kushchak/homebridge-homepod-radio#37]
Heya!
I am having issues playing files to my HomePod:

```
[6/24/2023, 9:45:30 PM] [HomepodRadioPlatform] Started playing file: /homebridge/siren.mp3
[6/24/2023, 9:45:30 PM] [HomepodRadioPlatform] [HomePod Radio] Stopping playback - received stop request from PlatformWebActions 
[6/24/2023, 9:45:30 PM] [HomepodRadioPlatform] [HomePod Radio] Skipped storing state
[6/24/2023, 9:45:31 PM] Error: Command failed: atvremote --id *censored* stream_file=/homebridge/siren.mp3
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 762, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 535, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 650, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 700, in _handle_device_command
    return await _exec_command(atv.stream, cmd, True, *cmd_args)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/scripts/atvremote.py", line 729, in _exec_command
    value = await tmp(*args)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/core/facade.py", line 369, in stream_file
    await self.relay("stream_file")(file, metadata=metadata, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/raop/__init__.py", line 352, in stream_file
    await client.initialize(self.core.service.properties)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/raop/stream_client.py", line 375, in initialize
    await self._protocol.setup(self.timing_client.port, self.control_client.port)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/raop/protocols/airplayv2.py", line 38, in setup
    verifier = await verify_connection(
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/airplay/auth/__init__.py", line 104, in verify_connection
    has_encryption_keys = await verifier.verify_credentials()
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/airplay/auth/hap_transient.py", line 57, in verify_credentials
    resp = await self.http.post(
  File "/usr/local/lib/python3.8/dist-packages/pyatv/support/http.py", line 418, in post
    return await self.send_and_receive(
  File "/usr/local/lib/python3.8/dist-packages/pyatv/support/http.py", line 473, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: HTTP/1.1 method POST failed with code 470: Connection Authorization Required

>>> An error occurred, full stack trace above

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

Unsure what is going on here? I have tried both POST and GET
Thanks!

**Comment by petro-kushchak** [comment]
Hi, did you try to change you HomePod access policy ("HomePod access setup" section of readme)?
