### ISSUE TITLE
Error: This callback function has already been called by someone else; it can only be called one time

### ISSUE THREAD

**Issue by giuliomagnifico** [petro-kushchak/homebridge-homepod-radio#38]
Hello, thank for this plugin that seems great, I integrated it in my HomeBridge installation (with some issue to compile atvremote) but now when I try to play something via a shortcut I get this error:

As a straming url I'm using http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one for test.

```
[05/09/2023, 08:44:04] [@petro-kushchak/homebridge-homepod-radio] [Rai News 24] Triggered SET TargetMediaState: 0
[05/09/2023, 08:44:04] [@petro-kushchak/homebridge-homepod-radio] [Rai News 24] Triggered SET Speaker ON: 0
[05/09/2023, 08:44:04] [@petro-kushchak/homebridge-homepod-radio] [Rai News 24] Started hearbeat 619
[05/09/2023, 08:44:04] [@petro-kushchak/homebridge-homepod-radio] [Rai News 24] Started streaming http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one
Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/src/lib/homebridgeCallbacks.ts:19:34
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[05/09/2023, 08:44:04] [@petro-kushchak/homebridge-homepod-radio] Child bridge process ended
[05/09/2023, 08:44:04] [@petro-kushchak/homebridge-homepod-radio] Process Ended. Code: 1, Signal: null
[05/09/2023, 08:44:11] [@petro-kushchak/homebridge-homepod-radio] Restarting Process...
```

Thanks

**Comment by petro-kushchak** [comment]
Hi, interesting... Could you share more details on which version of the plugin + pyatv are you using?

**Comment by giuliomagnifico** [comment]
Thanks for the reply, I was using the v2.0.0 now I just updated to v3.0.0 (congrats on the release). But I got the same issue and error.

```
@petro-kushchak/homebridge-homepod-radio v3.0.0
atvremote 0.14.0
```

![IMG_C56F7001482A-1](https://github.com/petro-kushchak/homebridge-homepod-radio/assets/1975176/e7c6cf71-a124-4b80-8d80-6db8d861cde0)


```
[07/09/2023, 12:15:39] [@petro-kushchak/homebridge-homepod-radio] [Rai News 24] Triggered SET TargetMediaState: 0
[07/09/2023, 12:15:39] [@petro-kushchak/homebridge-homepod-radio] [Rai News 24] Triggered SET Speaker ON: 0
[07/09/2023, 12:15:39] [@petro-kushchak/homebridge-homepod-radio] [Rai News 24] Started hearbeat 1341
[07/09/2023, 12:15:39] [@petro-kushchak/homebridge-homepod-radio] [Rai News 24] Started streaming http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one
Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/src/lib/homebridgeCallbacks.ts:19:34
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[07/09/2023, 12:15:39] [@petro-kushchak/homebridge-homepod-radio] Child bridge process ended
```

**Comment by giuliomagnifico** [comment]
Okay, got it, but now I'm facing another error:


```
[08/09/2023, 08:01:19] [@petro-kushchak/homebridge-homepod-radio] [Rai News bagno Switch] SET ON: true
[08/09/2023, 08:01:19] [@petro-kushchak/homebridge-homepod-radio] [Rai News bagno] Started hearbeat 1029
[08/09/2023, 08:01:19] [@petro-kushchak/homebridge-homepod-radio] [Rai News bagno] Started streaming http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one
[08/09/2023, 08:01:34] [@petro-kushchak/homebridge-homepod-radio] [Rai News bagno] streaming exit: code 0 signal null
[08/09/2023, 08:01:34] [@petro-kushchak/homebridge-homepod-radio] [Rai News bagno] Cleared hearbeat 1029 - stop requested
[08/09/2023, 08:01:34] [@petro-kushchak/homebridge-homepod-radio] [Rai News bagno] Error while trying to stop: Error: Command failed: kill -9 18426
/bin/sh: 1: kill: No such process
```

And I have another issue, I have one HomePod Mini in bathroom and home HomePod in the lounge room, I added both to the config but I see only the HomePod Mini and not the other HomePod, I mean that if I search to add the other "switch/speaker/volume" I don't find the second one ("Rai News salotto"), ony the one I already added ("Rai News bagno"), here's my config:

```
        {
            "homepodId": "94:EA:32:95:B0:58",
            "httpPort": 7654,
            "enableVolumeControl": true,
            "verboseMode": false,
            "radios": [
                {
                    "name": "Rai News bagno",
                    "radioUrl": "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",
                    "onSwitch": true,
                    "artworkUrl": "https://www.rainews.it/dl/rainews/images/social/live.png"
                }
            ],
            "_bridge": {
                "username": "0E:2C:21:51:C6:96",
                "port": 49312
            },
            "platform": "HomepodRadioPlatform"
        },
        {
            "homepodId": "ACBCB5F31293",
            "httpPort": 7654,
            "enableVolumeControl": true,
            "verboseMode": false,
            "radios": [
                {
                    "name": "Rai News salotto",
                    "radioUrl": "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=1&output=16",
                    "onSwitch": true
                }
            ],
            "platform": "HomepodRadioPlatform"
        }
    ],

```

**Comment by giuliomagnifico** [comment]
I'm debugging this issue and I've found that I'm also not able to start the streaming from the shell. So maybe it's not a plugin issue but something with ffmpeg, I know nothing about it unfortunately, here's the log:

```
pi@homebridge:~ $ ffmpeg -i https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=1&output=16 -f mp3 - | atvremote --id 94:EA:32:95:B0:58 stream_file=-
[3] 15133
-bash: -f: command not found
ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
New power state: Off
2023-09-08 13:37:20 ERROR [root]: Failed to parse metadata
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 263, in get_buffered_io_metadata
    return await get_metadata(buffer)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/metadata.py", line 25, in get_metadata
    in_file = await loop.run_in_executor(None, _open_file, file)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/support/metadata.py", line 15, in _open_file
    in_file = MediaFile(file)
  File "/home/pi/.local/lib/python3.9/site-packages/mediafile.py", line 165, in wrapper
    return mutagen_call('loadfile', '', f, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/mediafile.py", line 137, in mutagen_call
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/mediafile.py", line 1586, in __init__
    raise FileTypeError(self.filename)
mediafile.FileTypeError: 'stream': not in a recognized format
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 974, in _run_application
    return await cli_handler(loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 858, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, storage, loop)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 912, in _handle_device_command
    return await _exec_command(atv.stream, cmd, True, *cmd_args)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 941, in _exec_command
    value = await tmp(*args)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/core/facade.py", line 371, in stream_file
    await self.relay("stream_file")(
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 357, in stream_file
    audio_file = await open_source(
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 732, in open_source
    return await BufferedIOBaseSource.open(source, sample_rate, channels, sample_size)
  File "/home/pi/.local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 338, in open
    src = await loop.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/miniaudio.py", line 1268, in stream_any
    raise DecodeError("failed to init decoder", result)
miniaudio.DecodeError: ('failed to init decoder', -17)

>>> An error occurred, full stack trace above

[3]+  Stopped                 ffmpeg -i https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=1
```

**Comment by giuliomagnifico** [comment]
Edit, sorry for the 3 posts, but I found the issue, is the streaming url! 

https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=1&output=16

Probably because it creates a unique ID everytime is launched, and via ffmpeg it doesn't work. I don't know why. If I open the above url in my browser the url redirects to

https://rainews1-live.akamaized.net/hls/live/598326/rainews1/rainews1/playlist.m3u8?hdnea=st=1694174121~exp=1694174271~acl=/*~hmac=807e6946eac9ef681a4f111bf0af04d140eac44648f88ef8584eb0446ca8a100

and if I use this url in your plugin, then it works perfectly also via Home app!

Any tip for this issue?

**Comment by petro-kushchak** [comment]
Interesting - technically I could add to plugin support of some kind of "evaluation of final url after redirects", but probably there are already existing solutions for this...  Maybe you can get another url for that radio stream?

**Comment by giuliomagnifico** [comment]
No unfortunately I can’t use other links, this is the official link that works in IINA, VLC, Apple TV, etc… there isn’t a setting/variable to pass to ffmpeg to avoid the issue?

**Comment by petro-kushchak** [comment]
Ok, will prepare some beta build in a next few days :)

**Comment by petro-kushchak** [comment]
@giuliomagnifico  try to install v3.0.2-alpha, I've added `validateRadioUrl` setting (default false) - if set to `true` plugins will use `follow-redirects` library to evaluate final url :)


To install alpha/beta versions use this how-to:
https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by giuliomagnifico** [comment]
Hi @petro-kushchak thank you very much for this alpha.

It works! 🥳 and it's also quite reliable the audio, switch and shortcut. 

But the light on the HomePod Mini is not very reliable, I mean, when it's playing some times the white backlight is active, and sometimes not. Not sure why, it's annoying because without the light is harder to see the + and - buttons on it.

If you need I can make other tests.

I'm only not understanding why it doesn't work for the normal HomePod (not mini), it shouldn't be the same? I mean, the protocols are the same, why it isn't working?

If I try to add a second `homepodId`with the big HomePod and the same switch, I'm unable to find it when I search for a new accessory in Home app.

**Comment by petro-kushchak** [comment]
Hi, great - will prepare release then!

Regarding multiple HomePod support - its not supported yet, maybe in few weeks if I get enough time
