### ISSUE TITLE
Cannot identify the error 

### ISSUE THREAD

**Issue by dealex63** [petro-kushchak/homebridge-homepod-radio#43]
I have tried the latest build and 3.0.5 alpha both are unable stream. 
The stream url is https://rthk.hk/live2.m3u and I have also tick the validate radio stream url in the UI.
current setup is:
`homebridge-homepod-radio v3.0.5`
`atvremote 0.14.0`
`ffmpeg version6.0-homebridge-alpine-x86_64-static`

![image](https://github.com/petro-kushchak/homebridge-homepod-radio/assets/34654522/e4f76afa-3508-4915-abd4-9da72c918c7f)
![image](https://github.com/petro-kushchak/homebridge-homepod-radio/assets/34654522/1e9235d6-79d8-4848-bc86-f462ec8bb864)

[12/6/2023, 8:43:42 PM] [HomepodRadioPlatform] [RTHK radio 2] streaming data:   File "/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 392, in internal_stream_url
    await self.atv.stream_buffer(reader, metadata)
  File "/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 220, in stream_buffer
    await self.atv.stream.stream_file(stream, metadata)
  File "/usr/local/lib/python3.10/dist-packages/pyatv/core/facade.py", line 371, in stream_file
    await self.relay("stream_file")(
  File "/usr/local/lib/python3.10/dist-packages/pyatv/protocols/raop/__init__.py", line 360, in stream_file
    audio_file = await open_source(
  File "/usr/local/lib/python3.10/dist-packages/pyatv/protocols/raop/audio_source.py", line 732, in open_source
    return await BufferedIOBaseSource.open(source, sample_rate, channels, sample_size)
  File "/usr/local/lib/python3.10/dist-packages/pyatv/protocols/raop/audio_source.py", line 338, in open
    src = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/miniaudio.py", line 1268, in stream_any
    raise DecodeError("failed to init decoder", result)
miniaudio.DecodeError: ('failed to init decoder', -17)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 271, in stream_url
    await asyncio.gather(
  File "/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 401, in internal_stream_url
    await self.internal_stream_url(metadata, reader, retry_count + 1)
  File "/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 401, in internal_stream_url
    await self.internal_stream_url(metadata, reader, retry_count + 1)
  File "/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 401, in internal_stream_url
    await self.internal_stream_url(metadata, reader, retry_count + 1)
  File "/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 403, in internal_stream_url
    raise ex
  File "/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 392, in internal_stream_url
    await self.atv.stream_buffer(reader, metadata)
  File "/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/dist/stream.py", line 220, in stream_buffer
    await self.atv.stream.stream_file(stream, metadata)
  File "/usr/local/lib/python3.10/dist-packages/pyatv/core/facade.py", line 371, in stream_file
    await self.relay("stream_file")(
  File "/usr/local/lib/python3.10/dist-packages/pyatv/protocols/raop/__init__.py", line 360, in stream_file
    audio_file = await open_source(
  File "/usr/local/lib/python3.10/dist-packages/pyatv/protocols/raop/audio_source.py", line 732, in open_source
    return await BufferedIOBaseSource.open(source, sample_rate, channels, sample_size)
  File "/usr/local/lib/python3.10/dist-packages/pyatv/protocols/raop/audio_source.py", line 338, in open
    src = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/miniaudio.py", line 1268, in stream_any
    raise DecodeError("failed to init decoder", result)
miniaudio.DecodeError: ('failed to init decoder', -17)

[12/6/2023, 8:43:42 PM] [HomepodRadioPlatform] [RTHK radio 2] Playback heartbeat, source: streaming
[12/6/2023, 8:43:42 PM] [HomepodRadioPlatform] [RTHK radio 2] streaming data: 2023-12-06 20:43:42 DEBUG [pyatv.protocols.airplay.mrp_connection]: Closing connection
2023-12-06 20:43:42 DEBUG [pyatv.protocols.airplay.mrp_connection]: Disconnected from device: None
2023-12-06 20:43:42 DEBUG [pyatv.core.protocol]: Stopping heartbeat loop at 3 (AirPlay:192.168.50.184)
2023-12-06 20:43:42 DEBUG [pyatv.support.http]: Connection closed
2023-12-06 20:43:42 DEBUG [pyatv.auth.hap_channel]: Connection was lost to remote

[12/6/2023, 8:43:42 PM] [HomepodRadioPlatform] [RTHK radio 2] Playback heartbeat, source: streaming
[12/6/2023, 8:43:42 PM] [HomepodRadioPlatform] [RTHK radio 2] streaming exit: code 0 signal null
[12/6/2023, 8:43:42 PM] [HomepodRadioPlatform] [RTHK radio 2] Killing process: streaming: 17604
[12/6/2023, 8:43:42 PM] [HomepodRadioPlatform] [RTHK radio 2] Cleared hearbeat 7599 - stop requested
[12/6/2023, 8:43:42 PM] [HomepodRadioPlatform] [RTHK radio 2] Error while trying to stop: Error: Command failed: kill -9 17604
/bin/sh: 1: kill: No such process
I think I have configured everything right, can someone try it out for me is it just the stream url not supported.

**Comment by dealex63** [comment]
Then when I tried using this stram url: http://lstn.lv/bbc.m3u8?station=bbc_6music&bitrate=320000
It has returned below error
[12/6/2023, 10:00:42 PM] [HomepodRadioPlatform] [RTHK radio 2 Switch] GET ON
[12/6/2023, 10:00:45 PM] [HomepodRadioPlatform] [RTHK radio 2 Switch] SET ON: true
[12/6/2023, 10:00:45 PM] [HomepodRadioPlatform] [RTHK radio 2] Starting validating radio url
[12/6/2023, 10:00:45 PM] AssertionError [ERR_ASSERTION]: protocol mismatch
    at Object.request (/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/node_modules/follow-redirects/index.js:533:14)
    at HomepodRadioPlatformAccessory.startPlaying (/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/src/platformRadioAccessory.ts:148:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/6/2023, 10:00:45 PM] Got SIGTERM, shutting down Homebridge...
[12/6/2023, 10:00:45 PM] [HomepodRadioPlatform] Platform: shutdown...
[12/6/2023, 10:00:45 PM] [HomepodRadioPlatform] [RTHK radio 2] Skipped storing state
[12/6/2023, 10:00:50 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/6/2023, 10:00:55 PM] [HB Supervisor] Restarting Homebridge...

**Comment by dealex63** [comment]
Nvm. I managed to get it to play by updating the homepod mini to the latest version, and find an alternative link this channel which is http://rthkaudio2-lh.akamaihd.net/i/radio2_1@355865/master.m3u8
