### ISSUE TITLE
More than one platform

### ISSUE THREAD

**Issue by Githubmoses** [petro-kushchak/homebridge-homepod-radio#46]
Docker on synology NAS, latest version up to, but not including, beta.

I have been successful at getting mp3's to play and radio station on one homepod.  Imported child bridge to homekit, worked great.  I would like to add a second platform for a second deviceID (homepod), but I can't change the platform name or add more devices. 

I attempt to add a new homepod ID and new radio stations for that homepod, appears fine, but the server continually resets, original homepod setup volume control disconnects and nothing works.

I am guessing there is something I'm not doing properly?

**Comment by Githubmoses** [comment]
Got it!  For some reason a day or two later it just worked.  I did use the very first "issues" comments' suggestion of using port 4567 for the second one and it worked.  I will literally use those subsequent ports.  It worked!  Thank you so much for this.

**Comment by Githubmoses** [comment]
I did attempt to use port "4567" as the original Issues commenter did.  Still nothing.  Get the following errors:

AssertionError [ERR_ASSERTION]: protocol mismatch
    at Object.request (/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/node_modules/follow-redirects/index.js:530:14)
    at HomepodRadioPlatformAccessory.startPlaying (/homebridge/node_modules/@petro-kushchak/homebridge-homepod-radio/src/platformRadioAccessory.ts:148:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

The original entry works great.  I just can't add additional homepods with their own radio streams.

**Comment by justjam2013** [comment]
[](https://github.com/petro-kushchak/homebridge-homepod-radio/issues/2)
